# Generated by Django 5.2.12 on 2026-05-02 21:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CookieCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
                ('gdpr_consent_required', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'cookie categories',
                'db_table': 'webservers_cookiecategory',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_name', models.TextField(unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('expires', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'webservers_domain',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='OpenCookieDatabase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('platform', models.TextField(blank=True, null=True)),
                ('cookie_name', models.TextField()),
                ('domain', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('retention_period', models.TextField(blank=True, null=True)),
                ('data_controller', models.TextField(blank=True, null=True)),
                ('privacy_rights_portals', models.TextField(blank=True, null=True)),
                ('wildcard_match', models.BooleanField(default=False)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opencookies', to='webservers.cookiecategory')),
            ],
            options={
                'verbose_name': 'open cookie database entry',
                'verbose_name_plural': 'open cookie database',
                'db_table': 'webservers_opencookiedatabase',
                'ordering': ['cookie_name'],
            },
        ),
        migrations.CreateModel(
            name='Subdomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subdomain', models.TextField()),
                ('date_scanned', models.DateField()),
                ('webserver_down', models.BooleanField(default=False)),
                ('expires', models.DateField(blank=True, null=True)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subdomains', to='webservers.domain')),
            ],
            options={
                'db_table': 'webservers_subdomain',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_start', models.DateField()),
                ('time_end', models.DateField()),
                ('scan_closed', models.BooleanField(default=False)),
                ('header_name', models.TextField()),
                ('header_value', models.TextField()),
                ('subdomain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='headers', to='webservers.subdomain')),
            ],
            options={
                'db_table': 'webservers_header',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Cookie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_start', models.DateField()),
                ('time_end', models.DateField()),
                ('scan_closed', models.BooleanField(default=False)),
                ('cookie_name', models.TextField()),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cookies', to='webservers.cookiecategory')),
                ('subdomain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cookies', to='webservers.subdomain')),
            ],
            options={
                'db_table': 'webservers_cookie',
                'ordering': ['id'],
            },
        ),
        migrations.AddConstraint(
            model_name='subdomain',
            constraint=models.UniqueConstraint(fields=('domain', 'subdomain'), name='unique_subdomain_per_domain'),
        ),
        migrations.AddConstraint(
            model_name='header',
            constraint=models.UniqueConstraint(condition=models.Q(('scan_closed', False)), fields=('subdomain', 'header_name', 'header_value'), name='unique_open_header_per_subdomain'),
        ),
        migrations.AddConstraint(
            model_name='cookie',
            constraint=models.UniqueConstraint(condition=models.Q(('scan_closed', False)), fields=('subdomain', 'cookie_name'), name='unique_open_cookie_per_subdomain'),
        ),
    ]
