# Generated by Django 5.2.12 on 2026-05-02 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webservers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subdomain',
            name='expires',
        ),
        migrations.RemoveField(
            model_name='subdomain',
            name='webserver_down',
        ),
        migrations.AddField(
            model_name='subdomain',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='cookie',
            name='cookie_name',
            field=models.CharField(max_length=4096),
        ),
        migrations.AlterField(
            model_name='cookiecategory',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='domain',
            name='domain_name',
            field=models.CharField(max_length=253, unique=True),
        ),
        migrations.AlterField(
            model_name='header',
            name='header_name',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='header',
            name='header_value',
            field=models.CharField(max_length=16384),
        ),
        migrations.AlterField(
            model_name='opencookiedatabase',
            name='cookie_name',
            field=models.CharField(max_length=4096),
        ),
        migrations.AlterField(
            model_name='opencookiedatabase',
            name='data_controller',
            field=models.CharField(blank=True, max_length=4096, null=True),
        ),
        migrations.AlterField(
            model_name='opencookiedatabase',
            name='description',
            field=models.CharField(blank=True, max_length=4096, null=True),
        ),
        migrations.AlterField(
            model_name='opencookiedatabase',
            name='domain',
            field=models.CharField(blank=True, max_length=4096, null=True),
        ),
        migrations.AlterField(
            model_name='opencookiedatabase',
            name='platform',
            field=models.CharField(blank=True, max_length=4096, null=True),
        ),
        migrations.AlterField(
            model_name='opencookiedatabase',
            name='privacy_rights_portals',
            field=models.CharField(blank=True, max_length=4096, null=True),
        ),
        migrations.AlterField(
            model_name='opencookiedatabase',
            name='retention_period',
            field=models.CharField(blank=True, max_length=4096, null=True),
        ),
        migrations.AlterField(
            model_name='subdomain',
            name='subdomain',
            field=models.CharField(max_length=253),
        ),
    ]
